import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import './globals.css';
import Providers from '@/lib/redux/Provider';
import Navbar from '@/components/controller/navbar';
import Footer from '@/components/controller/footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			data-theme="luxury"
			suppressHydrationWarning>
			<body
				className={`antialiased min-h-screen transition-all duration-300 flex flex-col gap-5`}>
				<Providers>
					{/* <SocketProvider> */}
					<ThemeProvider>
						<Navbar />
						{children}
						<Footer />
					</ThemeProvider>
					{/* </SocketProvider> */}
				</Providers>
			</body>
		</html>
	);
}
